// GENERATED by apps/tui/scripts/generate-plugins.ts — do not edit.

import { portToken, type DependencyContainer } from '@dltech/atlas-harness'

import { NativePlugin } from './plugin'
import Github from './github'

export const NATIVE_PLUGIN_IDS: readonly string[] = ['github']

const NATIVE_PLUGINS = [
  Github,
] as const

export function registerNativePlugins({ container }: { container: DependencyContainer }): void {
  for (const plugin of NATIVE_PLUGINS) {
    container.register(portToken(NativePlugin), { useClass: plugin })
  }
}
