// GENERATED by apps/tui/scripts/generate-plugins.ts — do not edit.

import type { DependencyContainer } from '@dltech/atlas-harness'

import { registerPlugin as registerGithub } from './github'

export const NATIVE_PLUGIN_IDS: readonly string[] = ['github']

export function registerNativePlugins({ container }: { container: DependencyContainer }): void {
  registerGithub({ container })
}
