// design-sync prebuild for the Atlas UI primitives (durable sync input).
// Runs before package-build.mjs (wired as cfg.buildCmd). Two jobs:
//   1. Emit the bundle entry barrel — a single module re-exporting the six
//      web/src/components/ui/*.tsx files, so --entry gives the converter ALL
//      13 exported components (a bare --entry <one file> would ship only that
//      file's exports). It lives under web/ so PKG_DIR anchors to the web app.
//   2. Compile web/src/app/globals.css (Tailwind v4 source) into a static
//      stylesheet (cfg.cssEntry) — see .design-sync/tw-compile.css.
// Both outputs land in the gitignored web/.design-sync-build/ (regenerated
// every build; nothing to commit but this script + tw-compile.css).
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(repoRoot, 'web/.design-sync-build');
mkdirSync(outDir, { recursive: true });

// The six UI-primitive source files (relative to the barrel's location).
const files = ['button', 'card', 'badges', 'brand', 'field', 'spinner'];
const barrel =
  '// AUTO-GENERATED by .design-sync/prebuild.mjs — the design-sync bundle entry.\n' +
  files.map((f) => `export * from '../src/components/ui/${f}';`).join('\n') +
  '\n';
writeFileSync(resolve(outDir, 'entry.tsx'), barrel);

// Compile the shippable stylesheet.
execSync(
  'node .ds-sync/node_modules/.bin/tailwindcss ' +
    '-i .design-sync/tw-compile.css -o web/.design-sync-build/styles.css',
  { cwd: repoRoot, stdio: 'inherit' },
);
