import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';

/**
 * One streamed worker event in a session's transcript (a thinking step, a tool call, or a report).
 * This table is the SINGLE SOURCE OF TRUTH for the harness-visible transcript — check_session and
 * searchTranscript read it, and it survives restarts. (The engine's own on-disk JSONL under the
 * engine home is separate and opaque: it's the SDK's private resume blob, addressed only by
 * `Session.engine_session_id`, never read here.)
 *
 * Append-only, ordered by the autogenerated `id`. Single `created_at` (no updated_at) — events are
 * immutable once written.
 */
@Entity({ name: 'session_events' })
@Index(['session_id'])
export class SessionEvent {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id!: string;

  /** The session this event belongs to (no FK — house style is FK-less raw SQL). */
  @Column({ type: 'text' })
  session_id!: string;

  // 'text' (thinking) | 'tool' (a tool call) | 'result' (a report).
  @Column({ type: 'text' })
  kind!: string;

  /** The text of a 'text'/'result' event (null for 'tool'). */
  @Column({ type: 'text', nullable: true })
  text!: string | null;

  /** The tool name of a 'tool' event (null otherwise). */
  @Column({ type: 'text', nullable: true })
  name!: string | null;

  /** Optional detail string of a 'tool' event. */
  @Column({ type: 'text', nullable: true })
  detail!: string | null;

  @CreateDateColumn({ type: 'timestamptz', update: false })
  created_at!: Date;
}
