import { env } from '@/lib/env';
import { createClient } from '@dltech/pgbase/client';
import type { PgbaseModels } from '@workspace/shared/pgbase';
import { io } from 'socket.io-client';

/**
 * App-singleton pgbase client — ONE muxed socket.io connection for every live query in the app
 * (replaces the old `@workspace/pg-realtime` `RealtimeClient`). Unlike the old client, constructing
 * this opens nothing: the socket connects lazily on the first live query, so there's no SSR guard
 * needed here.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Row types
// ─────────────────────────────────────────────────────────────────────────────
// `@workspace/shared/pgbase` is generated by the same `prisma generate` the backend runs, so a column
// added or retyped in the schema is a compile error here rather than a runtime surprise. Two things
// the generator cannot know, because policies are TypeScript and it runs before them — both restated
// verbatim from the pgbase policy registry:
//
//   - a model with NO_CLIENT_ACCESS is not reachable from the browser at all (the 7 omitted keys)
//   - a column a policy `omit`s never reaches the wire (the per-model `Omit<...>`s below)
//
// `Job` and `Thread` omit nothing. `Subagent` is a `Pick` rather than an `Omit`: it's a short
// allowlist (`id`/`orgId`/`status`/`endedAt` — the two fields the old `ThreadMessage` join used to
// deliver, plus the identity/scoping columns), and `Pick` fails loudly if the policy ever widens,
// which is what we want given `omit` fails open.
export type Models = Omit<
  PgbaseModels,
  | 'McpServer'
  | 'OrgCredential'
  | 'Skill'
  | 'User'
  | 'WorkspaceMount'
  | 'WorkspaceProfile'
  | 'WorkspaceSecretFile'
> & {
  readonly AgentCredential: Omit<
    PgbaseModels['AgentCredential'],
    'scopes' | 'materialEnc' | 'lastRefreshedAt' | 'updatedAt'
  >;
  readonly InboundMessage: Omit<PgbaseModels['InboundMessage'], 'deliveredAt' | 'updatedAt'>;
  readonly Organization: Omit<PgbaseModels['Organization'], 'createdAt' | 'updatedAt'>;
  readonly OrganizationMember: Omit<PgbaseModels['OrganizationMember'], 'createdAt' | 'updatedAt'>;
  readonly Repo: Omit<PgbaseModels['Repo'], 'createdAt' | 'updatedAt'>;
  readonly Subagent: Pick<PgbaseModels['Subagent'], 'id' | 'orgId' | 'status' | 'endedAt'>;
  readonly Task: Omit<PgbaseModels['Task'], 'createdAt' | 'updatedAt'>;
  readonly ThreadGroup: Omit<PgbaseModels['ThreadGroup'], 'createdAt' | 'updatedAt'>;
  readonly ThreadMessage: Omit<
    PgbaseModels['ThreadMessage'],
    'audience' | 'authorId' | 'updatedAt'
  >;
};

/**
 * Auth: matches the old `RealtimeClient` exactly — the backend session is an httpOnly `access_token`
 * cookie, so there's no bearer token to hand over via `getAuth`. What actually carries the cookie is
 * `credentials: 'include'` on the read fetch and `withCredentials` on the socket, both below.
 */
export const pgbase = createClient<Models>({
  baseUrl: env.NEXT_PUBLIC_BACKEND_URL,
  fetch: (input, init) => fetch(input, { ...init, credentials: 'include' }),
  createSocket: (baseUrl, opts) =>
    io(baseUrl, { ...opts, withCredentials: true, transports: ['websocket', 'polling'] }),
});
