import type { ModelConfig, Row } from '@workspace/pg-realtime';
import type { Repository } from 'typeorm';
import type { OrganizationMember } from '../../_lib/database/entities/organization-member.entity';
import { JobRealtimeGuard } from './job.guard';

export function buildJobRealtimeModels(members: Repository<OrganizationMember>): ModelConfig[] {
  return [
    {
      table: 'jobs',
      name: 'jobs',
      primaryKey: 'id',
      guard: new JobRealtimeGuard(members),
      mapRow: (raw: Row): Row => ({
        id: raw.id,
        orgId: raw.org_id, // kept for the guard scope
        repoId: raw.repo_id,
        title: raw.title,
        status: raw.status,
        activity: raw.activity,
        kind: raw.kind,
        origin: raw.origin,
        focusedThreadId: raw.focused_thread_id,
        archivedAt: raw.archived_at,
        createdAt: raw.created_at,
        updatedAt: raw.updated_at,
      }),
    },
    {
      table: 'thread_groups',
      name: 'thread_groups',
      primaryKey: 'id',
      guard: new JobRealtimeGuard(members),
      mapRow: (raw: Row): Row => ({
        id: raw.id,
        orgId: raw.org_id,
        jobId: raw.job_id,
        ordinal: raw.ordinal,
        kind: raw.kind,
        title: raw.title,
        type: raw.type,
        status: raw.status,
        condition: raw.condition,
      }),
    },
    {
      table: 'threads',
      name: 'threads',
      primaryKey: 'id',
      guard: new JobRealtimeGuard(members),
      mapRow: (raw: Row): Row => ({
        id: raw.id,
        orgId: raw.org_id,
        jobId: raw.job_id,
        threadGroupId: raw.thread_group_id,
        role: raw.role,
        type: raw.type,
        parentThreadId: raw.parent_thread_id,
        ordinal: raw.ordinal,
        brief: raw.brief,
        status: raw.status,
        condition: raw.condition,
        sessionId: raw.session_id,
        createdAt: raw.created_at,
        updatedAt: raw.updated_at,
      }),
    },
    {
      table: 'thread_messages',
      name: 'thread_messages',
      primaryKey: 'id',
      guard: new JobRealtimeGuard(members),
      mapRow: (raw: Row): Row => ({
        id: raw.id,
        orgId: raw.org_id,
        jobId: raw.job_id,
        threadId: raw.thread_id,
        subagentId: raw.subagent_id,
        source: raw.source,
        isAtlas: raw.source === 'atlas',
        authorId: raw.author_id,
        author: raw.author,
        text: raw.text,
        kind: raw.kind,
        card: raw.card,
        meta: raw.meta,
        orderAt: raw.order_at,
        postedAt: raw.created_at,
      }),
    },
    {
      table: 'tasks',
      name: 'tasks',
      primaryKey: 'id',
      guard: new JobRealtimeGuard(members),
      mapRow: (raw: Row): Row => ({
        id: raw.id,
        orgId: raw.org_id,
        jobId: raw.job_id,
        threadGroupId: raw.thread_group_id,
        ordinal: raw.ordinal,
        title: raw.title,
        brief: raw.brief,
        activeForm: raw.active_form,
        status: raw.status,
        blockedBy: raw.blocked_by,
      }),
    },
  ];
}
