// GENERATED by packages/harness/prisma/embed-migrations.ts — do not edit.

import type { Migration } from 'prisma-adapter-bun-sqlite'

export const EMBEDDED_MIGRATIONS: readonly Migration[] = [
  {
    name: '20260824000000_init',
    sql: `-- CreateTable
CREATE TABLE "Branch" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT,
    "head" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TEXT NOT NULL,
    "updatedAt" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Event" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "branchId" TEXT NOT NULL,
    "seq" INTEGER NOT NULL,
    "runId" TEXT NOT NULL,
    "parentRunId" TEXT,
    "depth" INTEGER NOT NULL,
    "at" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "contextSlot" TEXT,
    "contextKey" TEXT,
    CONSTRAINT "Event_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "Branch_updatedAt_idx" ON "Branch"("updatedAt");

-- CreateIndex
CREATE INDEX "Event_branchId_type_idx" ON "Event"("branchId", "type");

-- CreateIndex
CREATE UNIQUE INDEX "Event_branchId_seq_key" ON "Event"("branchId", "seq");

-- CreateIndex
CREATE UNIQUE INDEX "Event_branchId_contextSlot_contextKey_key" ON "Event"("branchId", "contextSlot", "contextKey");

`,
  },
  {
    name: '20260826000000_turn_ledger',
    sql: `-- CreateTable
CREATE TABLE "Turn" (
    "runId" TEXT NOT NULL PRIMARY KEY,
    "branchId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "modelId" TEXT NOT NULL,
    "steps" INTEGER NOT NULL,
    "inputTokens" INTEGER NOT NULL,
    "outputTokens" INTEGER NOT NULL,
    "cacheReadTokens" INTEGER NOT NULL,
    "cacheWriteTokens" INTEGER NOT NULL,
    "startedAt" TEXT NOT NULL,
    "endedAt" TEXT NOT NULL,
    "durationMs" INTEGER NOT NULL,
    CONSTRAINT "Turn_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "Turn_branchId_startedAt_idx" ON "Turn"("branchId", "startedAt");
`,
  },
  {
    name: '20260827000000_context_digest',
    sql: `-- AlterTable
ALTER TABLE "Event" ADD COLUMN "contextDigest" TEXT;

-- DropIndex
DROP INDEX "Event_branchId_contextSlot_contextKey_key";

-- CreateIndex
CREATE UNIQUE INDEX "Event_branchId_contextSlot_contextKey_contextDigest_key" ON "Event"("branchId", "contextSlot", "contextKey", "contextDigest");
`,
  },
  {
    name: '20260827010000_branch_fork',
    sql: `-- AlterTable
ALTER TABLE "Branch" ADD COLUMN "parentBranchId" TEXT;

-- AlterTable
ALTER TABLE "Branch" ADD COLUMN "forkSeq" INTEGER;

-- AlterTable
ALTER TABLE "Branch" ADD COLUMN "forkMode" TEXT;

-- CreateIndex
CREATE INDEX "Branch_parentBranchId_idx" ON "Branch"("parentBranchId");
`,
  },
  {
    name: '20260827173505_rename_branch_to_thread',
    sql: `DROP INDEX "Branch_parentBranchId_idx";
DROP INDEX "Branch_updatedAt_idx";
DROP INDEX "Event_branchId_type_idx";
DROP INDEX "Event_branchId_seq_key";
DROP INDEX "Event_branchId_contextSlot_contextKey_contextDigest_key";
DROP INDEX "Turn_branchId_startedAt_idx";

ALTER TABLE "Branch" RENAME TO "Thread";
ALTER TABLE "Thread" RENAME COLUMN "parentBranchId" TO "parentThreadId";
ALTER TABLE "Event" RENAME COLUMN "branchId" TO "threadId";
ALTER TABLE "Turn" RENAME COLUMN "branchId" TO "threadId";

CREATE INDEX "Thread_updatedAt_idx" ON "Thread"("updatedAt");
CREATE INDEX "Thread_parentThreadId_idx" ON "Thread"("parentThreadId");
CREATE INDEX "Event_threadId_type_idx" ON "Event"("threadId", "type");
CREATE UNIQUE INDEX "Event_threadId_seq_key" ON "Event"("threadId", "seq");
CREATE UNIQUE INDEX "Event_threadId_contextSlot_contextKey_contextDigest_key" ON "Event"("threadId", "contextSlot", "contextKey", "contextDigest");
CREATE INDEX "Turn_threadId_startedAt_idx" ON "Turn"("threadId", "startedAt");
`,
  },
  {
    name: '20260830000000_thread_workspace',
    sql: `-- AlterTable
ALTER TABLE "Thread" ADD COLUMN "workspace" TEXT;

-- AlterTable
ALTER TABLE "Thread" ADD COLUMN "repo" TEXT;

-- CreateIndex
CREATE INDEX "Thread_workspace_updatedAt_idx" ON "Thread"("workspace", "updatedAt");
`,
  },
  {
    name: '20260830120000_thread_lineage',
    sql: `-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Thread" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT,
    "head" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TEXT NOT NULL,
    "updatedAt" TEXT NOT NULL,
    "parentThreadId" TEXT,
    "forkSeq" INTEGER,
    "forkMode" TEXT,
    "spawnerThreadId" TEXT,
    "agentType" TEXT,
    "workspace" TEXT,
    "repo" TEXT,
    CONSTRAINT "Thread_parentThreadId_fkey" FOREIGN KEY ("parentThreadId") REFERENCES "Thread" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION,
    CONSTRAINT "Thread_spawnerThreadId_fkey" FOREIGN KEY ("spawnerThreadId") REFERENCES "Thread" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION
);
INSERT INTO "new_Thread" ("createdAt", "forkMode", "forkSeq", "head", "id", "parentThreadId", "repo", "title", "updatedAt", "workspace") SELECT "createdAt", "forkMode", "forkSeq", "head", "id", "parentThreadId", "repo", "title", "updatedAt", "workspace" FROM "Thread";
DROP TABLE "Thread";
ALTER TABLE "new_Thread" RENAME TO "Thread";
CREATE INDEX "Thread_updatedAt_idx" ON "Thread"("updatedAt");
CREATE INDEX "Thread_parentThreadId_idx" ON "Thread"("parentThreadId");
CREATE INDEX "Thread_spawnerThreadId_idx" ON "Thread"("spawnerThreadId");
CREATE INDEX "Thread_workspace_updatedAt_idx" ON "Thread"("workspace", "updatedAt");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
`,
  },
  {
    name: '20260901000000_thread_model',
    sql: `-- AlterTable
ALTER TABLE "Thread" ADD COLUMN "modelRef" TEXT;

-- AlterTable
ALTER TABLE "Thread" ADD COLUMN "modelEffort" TEXT;
`,
  },
  {
    name: '20260903120000_perf_samples',
    sql: `-- CreateTable
CREATE TABLE "PerfSample" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "pid" INTEGER NOT NULL,
    "bootedAt" TEXT NOT NULL,
    "workspace" TEXT,
    "startedAt" TEXT NOT NULL,
    "endedAt" TEXT NOT NULL,
    "cpuUserMs" INTEGER NOT NULL,
    "cpuSysMs" INTEGER NOT NULL,
    "lagP50Ms" REAL NOT NULL,
    "lagP95Ms" REAL NOT NULL,
    "lagMaxMs" REAL NOT NULL,
    "rssMb" INTEGER NOT NULL,
    "heapMb" INTEGER NOT NULL,
    "turnActive" BOOLEAN NOT NULL,
    "counters" TEXT NOT NULL
);

-- CreateIndex
CREATE INDEX "PerfSample_pid_startedAt_idx" ON "PerfSample"("pid", "startedAt");

-- CreateIndex
CREATE INDEX "PerfSample_startedAt_idx" ON "PerfSample"("startedAt");
`,
  },
]
