#!/usr/bin/env bun
/**
 * Bakes the committed migration SQL into a TypeScript module.
 *
 * `bun build --compile` produces a single executable with no filesystem beside it, and
 * `import.meta.url` inside one resolves to a virtual path — so the migrator's `readdirSync` found
 * nothing and every compiled binary died on startup with "no migrations directory".
 *
 * Reading the generated module instead of the directory means dev and the shipped binary run the
 * SAME code path, rather than the binary taking a fallback nobody exercises until release.
 *
 * Run by `pnpm build` and `pnpm db:migrate`; `migrator.spec.ts` fails if the generated file drifts
 * from `prisma/migrations`, so a forgotten regeneration is a red test rather than a broken release.
 */

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(here, '..', 'prisma', 'migrations');
const outFile = join(here, '..', 'src', 'store', 'migrations.generated.ts');

const names = readdirSync(migrationsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const entries = names.map((name) => {
  const sql = readFileSync(join(migrationsDir, name, 'migration.sql'), 'utf8');
  return { name, sql, checksum: createHash('sha256').update(sql).digest('hex') };
});

const body = entries
  .map(
    (m) =>
      `  {\n    name: ${JSON.stringify(m.name)},\n` +
      `    checksum: ${JSON.stringify(m.checksum)},\n` +
      `    sql: ${JSON.stringify(m.sql)},\n  },`,
  )
  .join('\n');

writeFileSync(
  outFile,
  `// GENERATED by scripts/embed-migrations.ts — do not edit.\n` +
    `// Regenerate with \`pnpm migrations:embed\` after adding a migration.\n` +
    `import type { PendingMigration } from './migrator.service.js';\n\n` +
    `export const EMBEDDED_MIGRATIONS: readonly PendingMigration[] = [\n${body}\n];\n`,
);

console.log(`embedded ${entries.length} migration(s) → src/store/migrations.generated.ts`);
