#!/usr/bin/env bun
/**
 * Vendors the Tree-sitter grammars listed in `parsers-config.json` into `src/ui/markdown/grammars/`.
 *
 * The download and codegen are OpenTUI's own `update-assets` script, which exists precisely so an
 * application can add grammars beyond the five it bundles. Wrapping it rather than reimplementing it
 * means the generated file keeps using `resolveBundledFilePath`, which is what makes the assets
 * survive `bun build --compile` — see the note in `grammars/index.ts`.
 *
 * The wrapper is here for one reason: the generated header tells the reader to run
 * `bun assets/update.ts`, a path that only exists inside the OpenTUI repo. A file that says
 * "DO NOT EDIT MANUALLY" has to name the command that regenerates it, or the next person edits it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const grammarsDir = join(root, 'src', 'ui', 'markdown', 'grammars');
const outFile = join(grammarsDir, 'parsers.generated.ts');

const updateAssets = fileURLToPath(import.meta.resolve('@opentui/core/tree-sitter/update-assets'));

const result = Bun.spawnSync(
  [
    process.execPath,
    updateAssets,
    '--config',
    join(grammarsDir, 'parsers-config.json'),
    '--assets',
    join(grammarsDir, 'assets'),
    '--output',
    outFile,
  ],
  { stdout: 'inherit', stderr: 'inherit' },
);

if (result.exitCode !== 0) {
  throw new Error(`update-assets exited with ${result.exitCode}`);
}

const UPSTREAM_HEADER = `// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file`;

const generated = readFileSync(outFile, 'utf8');
if (!generated.startsWith(UPSTREAM_HEADER)) {
  // Fail loud rather than shipping a file whose regeneration command is a guess.
  throw new Error(`unexpected header in ${outFile}; OpenTUI's generator changed — update this script`);
}

writeFileSync(
  outFile,
  generated.replace(
    UPSTREAM_HEADER,
    `// GENERATED by scripts/update-grammars.ts — do not edit.\n` +
      `// Regenerate with \`pnpm grammars:update\` after editing parsers-config.json.`,
  ),
);

console.log(`vendored grammars → src/ui/markdown/grammars/`);
