#!/usr/bin/env bun
import { existsSync } from 'node:fs'
import { join, relative } from 'node:path'

const packageRoot = join(import.meta.dir, '..')
const migrationsRoot = join(import.meta.dir, 'migrations')
const outFile = join(packageRoot, 'src', 'store', 'migrations.generated.ts')

const forTemplateLiteral = (text: string): string =>
  text.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${')

async function migrationDirectories(): Promise<readonly string[]> {
  if (!existsSync(migrationsRoot)) return []

  const glob = new Bun.Glob('*/migration.sql')
  const found: string[] = []
  for await (const file of glob.scan({ cwd: migrationsRoot, absolute: true })) found.push(file)

  return found.sort()
}

const files = await migrationDirectories()

const entries = await Promise.all(
  files.map(async (file) => {
    const name = relative(migrationsRoot, file).replace('/migration.sql', '')
    const sql = await Bun.file(file).text()
    return `  {\n    name: '${name}',\n    sql: \`${forTemplateLiteral(sql)}\`,\n  },`
  }),
)

const body = [
  '// GENERATED by packages/harness/prisma/embed-migrations.ts — do not edit.',
  '',
  "import type { Migration } from 'prisma-adapter-bun-sqlite'",
  '',
  'export const EMBEDDED_MIGRATIONS: readonly Migration[] = [',
  ...entries,
  ']',
  '',
].join('\n')

const unchanged = existsSync(outFile) && (await Bun.file(outFile).text()) === body
if (!unchanged) await Bun.write(outFile, body)

console.log(
  `migrations → ${relative(packageRoot, outFile)} (${files.length} embedded${unchanged ? ', unchanged' : ''})`,
)
