#!/usr/bin/env bun
import { existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const skillsRoot = join(repoRoot, 'packages', 'harness', 'skills')
const outFile = join(repoRoot, 'packages', 'harness', 'src', 'skills', 'manifest.generated.ts')

async function authoredSkills(): Promise<readonly string[]> {
  if (!existsSync(skillsRoot)) return []

  const glob = new Bun.Glob('**/*.md')
  const found: string[] = []
  for await (const file of glob.scan({ cwd: skillsRoot, absolute: true })) found.push(file)

  return found.sort()
}

const forTemplateLiteral = (text: string): string =>
  text.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${')

const files = await authoredSkills()

const entries = await Promise.all(
  files.map(async (file) => {
    const path = relative(skillsRoot, file)
    const text = await Bun.file(file).text()
    return `  {\n    path: '${path}',\n    text: \`${forTemplateLiteral(text)}\`,\n  },`
  }),
)

const body = [
  '// GENERATED by apps/tui/scripts/generate-skills.ts — do not edit.',
  '',
  'export const BUILT_IN_SKILLS: readonly { path: string; text: string }[] = [',
  ...entries,
  ']',
  '',
].join('\n')

await Bun.write(outFile, body)

console.log(`skills → ${relative(repoRoot, outFile)} (${files.length} skills)`)
