#!/usr/bin/env bun
import { existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const tuiRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const pluginsDir = join(tuiRoot, 'src', 'plugins')
const outFile = join(pluginsDir, 'manifest.generated.ts')

const localNameFor = (directory: string): string =>
  directory
    .split(/[-_]/)
    .map((part) => `${(part[0] ?? '').toUpperCase()}${part.slice(1)}`)
    .join('')

async function nativePluginDirectories(): Promise<string[]> {
  if (!existsSync(pluginsDir)) return []

  const found: string[] = []
  for await (const entry of new Bun.Glob('*/index.ts').scan({ cwd: pluginsDir })) {
    const directory = dirname(entry)
    if (directory === '__tests__') continue
    found.push(directory)
  }
  return found.sort()
}

const directories = await nativePluginDirectories()

const body = [
  '// GENERATED by apps/tui/scripts/generate-plugins.ts — do not edit.',
  '',
  "import { portToken, type DependencyContainer } from '@dltech/atlas-harness'",
  '',
  "import { NativePlugin } from './plugin'",
  ...directories.map((directory) => `import ${localNameFor(directory)} from './${directory}'`),
  '',
  `export const NATIVE_PLUGIN_IDS: readonly string[] = [${directories
    .map((directory) => `'${directory}'`)
    .join(', ')}]`,
  '',
  'const NATIVE_PLUGINS = [',
  ...directories.map((directory) => `  ${localNameFor(directory)},`),
  '] as const',
  '',
  'export function registerNativePlugins({ container }: { container: DependencyContainer }): void {',
  '  for (const plugin of NATIVE_PLUGINS) {',
  '    container.register(portToken(NativePlugin), { useClass: plugin })',
  '  }',
  '}',
  '',
].join('\n')

await Bun.write(outFile, body)

console.log(`plugins → ${relative(tuiRoot, outFile)} (${directories.length} plugins)`)
