#!/usr/bin/env bun
import { existsSync, mkdirSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const harnessSrc = join(repoRoot, 'packages', 'harness', 'src')
const outFile = join(harnessSrc, 'discovery', 'manifest.generated.ts')

const targets = [
  { dir: join(harnessSrc, 'hooks'), pattern: '**/*.hook.ts' },
  { dir: join(harnessSrc, 'tools'), pattern: '**/*.tool.ts' },
]

async function scan(args: { dir: string; pattern: string }): Promise<string[]> {
  if (!existsSync(args.dir)) return []
  const glob = new Bun.Glob(args.pattern)
  const found: string[] = []
  for await (const file of glob.scan({ cwd: args.dir, absolute: true })) {
    if (file.includes('/__tests__/')) continue
    found.push(file)
  }
  return found
}

const modules = (await Promise.all(targets.map(scan))).flat().sort()

const outDir = dirname(outFile)
mkdirSync(outDir, { recursive: true })

const specifierFor = (file: string): string => {
  const path = relative(outDir, file).replace(/\.ts$/, '')
  return path.startsWith('.') ? path : `./${path}`
}

const body = [
  '// GENERATED by apps/tui/scripts/generate-manifest.ts — do not edit.',
  '',
  ...modules.map((file) => `import '${specifierFor(file)}'`),
  ...(modules.length > 0 ? [''] : []),
  `export const MANIFEST_MODULE_COUNT = ${modules.length}`,
  '',
].join('\n')

await Bun.write(outFile, body)

console.log(`manifest → ${relative(repoRoot, outFile)} (${modules.length} modules)`)
