#!/usr/bin/env bun
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const grammarsDir = join(root, 'src', 'ui', 'markdown', 'grammars')
const outFile = join(grammarsDir, 'parsers.generated.ts')

const updateAssets = fileURLToPath(import.meta.resolve('@opentui/core/tree-sitter/update-assets'))

const result = Bun.spawnSync(
  [
    process.execPath,
    updateAssets,
    '--config',
    join(grammarsDir, 'parsers-config.json'),
    '--assets',
    join(grammarsDir, 'assets'),
    '--output',
    outFile,
  ],
  { stdout: 'inherit', stderr: 'inherit' },
)

if (result.exitCode !== 0) throw new Error(`update-assets exited with ${result.exitCode}`)

// OpenTUI's generator stamps its own header, naming a path that exists only inside its repo.
const UPSTREAM_HEADER = `// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file`

const generated = readFileSync(outFile, 'utf8')
if (!generated.startsWith(UPSTREAM_HEADER)) {
  throw new Error(
    `unexpected header in ${outFile}; OpenTUI's generator changed — update this script`,
  )
}

writeFileSync(
  outFile,
  generated.replace(UPSTREAM_HEADER, '// GENERATED from parsers-config.json — do not edit.'),
)

console.log('vendored grammars → src/ui/markdown/grammars/')
