import { mkdir, rm, symlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { LoadedSkill, McpServerConfig } from './skill.types';

/**
 * DB-FREE materializer for an employee's per-engine HOME. Pure file-writing functions extracted from
 * `EngineHomeProvisioner` so BOTH sides reuse the exact same disk layout:
 *  - HOST: `EngineHomeProvisioner` calls these after resolving code-declared ∪ Postgres grants.
 *  - DAEMON (Phase 3, no DB): primes the same homes from the inputs the host shipped over Redis.
 *
 * NO injected deps, NO DB, NO roster — just (home dir, skills/MCP) → files. Keep it that way so the
 * daemon image can import this file without pulling in any host/TypeORM code.
 */

/** Make the claude config dir's `skills/` folder an exact mirror of `skills` — the whole folder is
 * rebuilt so a skill removed from the set has its symlink pruned (not left orphaned). Idempotent. */
export async function writeClaudeHome(
  home: string,
  skills: LoadedSkill[],
): Promise<void> {
  const skillsDir = join(home, 'skills');
  await rm(skillsDir, { recursive: true, force: true });
  await mkdir(skillsDir, { recursive: true });
  for (const skill of skills) {
    await symlink(skill.dir, join(skillsDir, skill.name), 'dir');
  }
}

/** Mirror codex's `config.toml` (MCP) + `AGENTS.md` (skills listing) in CODEX_HOME — written when
 * non-empty, DELETED when empty so a cleared list doesn't leave a stale file behind. Idempotent. */
export async function writeCodexHome(
  home: string,
  mcpServers: ReadonlyArray<McpServerConfig>,
  skills: LoadedSkill[],
): Promise<void> {
  const configToml = join(home, 'config.toml');
  if (mcpServers.length)
    await writeFile(configToml, renderCodexMcpToml(mcpServers));
  else await rm(configToml, { force: true });

  const agentsMd = join(home, 'AGENTS.md');
  if (skills.length) await writeFile(agentsMd, renderSkillsMarkdown(skills));
  else await rm(agentsMd, { force: true });
}

const tomlStr = (v: string): string =>
  `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

/** Render `[mcp_servers.*]` blocks codex reads from CODEX_HOME/config.toml. stdio is fully
 * supported; http is best-effort (codex's streamable-http MCP schema varies by version). */
export function renderCodexMcpToml(
  servers: ReadonlyArray<McpServerConfig>,
): string {
  const blocks = servers.map((s) => {
    if (s.transport === 'stdio') {
      const lines = [
        `[mcp_servers.${s.name}]`,
        `command = ${tomlStr(s.command)}`,
      ];
      if (s.args?.length)
        lines.push(`args = [${s.args.map(tomlStr).join(', ')}]`);
      if (s.env && Object.keys(s.env).length) {
        lines.push(`[mcp_servers.${s.name}.env]`);
        for (const [k, v] of Object.entries(s.env))
          lines.push(`${k} = ${tomlStr(v)}`);
      }
      return lines.join('\n');
    }
    // http — best-effort; verify against the codex version in use.
    return [`[mcp_servers.${s.name}]`, `url = ${tomlStr(s.url)}`].join('\n');
  });
  return `# Generated by EngineHomeProvisioner — per-employee MCP servers. Do not edit by hand.\n\n${blocks.join('\n\n')}\n`;
}

export function renderSkillsMarkdown(skills: LoadedSkill[]): string {
  const items = skills
    .map((s) => `- **${s.name}** — ${s.description} (files at \`${s.dir}\`)`)
    .join('\n');
  return `# Skills available to you\n\nYou have these skills; read a skill's directory for its full instructions before using it.\n\n${items}\n`;
}
